[package]
name = "heng-controller"
version = "0.1.0"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
anyhow = "1.0.38"
serde = { version = "1.0.123", features = ["derive"] }
toml = "0.5.8"
validator = { version = "0.12.0", features = ["derive"] }
dotenv = "0.15.0"

[dependencies.tracing]
git = "https://github.com/tokio-rs/tracing.git"
rev = "881091a1dd5d3126faeabbca9e3779f1d16c3cce"

[dependencies.tracing-subscriber]
git = "https://github.com/tokio-rs/tracing.git"
rev = "881091a1dd5d3126faeabbca9e3779f1d16c3cce"

[dependencies.tracing-error]
git = "https://github.com/tokio-rs/tracing.git"
rev = "881091a1dd5d3126faeabbca9e3779f1d16c3cce"
