[judger]
remote_domain = "localhost:8080"
access_key = "example-ak"
secret_key = "example-sk"
rpc_timeout = 10000 # in milliseconds

[redis]
url = "redis://localhost:6379/1"
max_open = 10

[data]
directory = "/tmp/heng-judger/data"
download_size_limit = "64MiB"

[executor]
nsjail_config = "/etc/nsjail/sandbox.cfg"
workspace_root = "/tmp/heng-judger/workspace"
uid = 1025
gid = 1025

[executor.hard_limit]
cpu_time = 16000
memory = "512 MiB"
output = "256 MiB"
pids = 64

[executor.compilers]
gcc = "/usr/bin/gcc"
gxx = "/usr/bin/g++"
javac = "/usr/bin/javac"
rustc = "/usr/local/rust/bin/rustc"

[executor.runtimes]
java = "/usr/bin/java"
node = "/usr/bin/node"
python = "/usr/bin/python3"
