[judger]
remote_domain = "localhost:8080"
access_key = "example-ak"
secret_key = "example-sk"
rpc_timeout = 10000 # in milliseconds

[data]
directory = "/tmp/heng-judger/data"
download_size_limit = "64MiB"

[executor]
workspace_root = "/tmp/heng-judger/workspace"
uid = 1025
gid = 1025

[executor.hard_limit]
real_time = 32000
cpu_time = 16000
memory = "512 MiB"
output = "256 MiB"
pids = 64

[executor.c_cpp]
gcc = "/usr/bin/gcc"
gxx = "/usr/bin/g++"
mount = [
    "/usr/lib", 
    "/usr/include",
    "/usr/bin/cc",
    "/usr/bin/ld",
    "/usr/bin/as",
]

[executor.java]
java = "/usr/local/java/bin/java"
javac = "/usr/local/java/bin/javac"
mount = ["/usr/local/java"]

[executor.javascript]
node = "/usr/bin/node"
mount = ["/usr/lib"]

[executor.python]
python = "/usr/bin/python3"
mount = ["/usr/lib"]

[executor.rust]
rustc = "/usr/local/rust/bin/rustc"
mount = [
    "/usr/local/rust",
    "/usr/lib",
    "/usr/bin/cc",
    "/usr/bin/ld",
]

# [executor.compilers]
# gcc = "/usr/bin/gcc"
# gxx = "/usr/bin/g++"
# javac = "/usr/bin/javac"
# rustc = "/usr/local/rust/bin/rustc"

# [executor.runtimes]
# java = "/usr/bin/java"
# node = "/usr/bin/node"
# python = "/usr/bin/python3"
