on:
  push:
    branches:
      - master
    paths:
      - 'heng-judger/**'
  pull_request:
    branches:
      - master
    paths:
      - 'heng-judger/**'

name: heng-judger

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Link nodejs
        run: |
          sudo ln `which node` /usr/bin/node
      - name: Mount rust toolchain
        run: |
          sudo mkdir /usr/local/rust
          sudo mount --bind ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu /usr/local/rust
      - name: Mount java home
        run: |
          sudo mkdir /usr/local/java
          sudo mount --bind $JAVA_HOME /usr/local/java
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p heng-judger --tests
      - name: Integration test
        run: |
          cd heng-judger
          cargo test -p heng-judger ___ 2>&1 | grep Running | awk '{print $2}' > test_paths
          cat test_paths | xargs -I {} sudo {}  --test-threads=1
