on:
  push:
    branches:
      - master
    paths:
      - 'heng-sandbox/**'
  pull_request:
    branches:
      - master
    paths:
      - 'heng-sandbox/**'

name: heng-sandbox

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p heng-sandbox --tests
      - name: Integration test
        run: |
          cd heng-sandbox
          cargo test -p heng-sandbox ___ 2>&1 | grep Running | awk '{print $2}' > test_paths
          cat test_paths | xargs -I {} sudo {}  --test-threads=1
